node:
    build: .
    volumes: 
        - ./:/app
    working_dir: /app

yarn:
    build: .
    volumes: 
        - ./:/app
    working_dir: /app
    environment:
        VIRTUAL_HOST: words-admin.docker
        VIRTUAL_PORT: 3000
    ports:
        - "3000:3000"
    expose:
        - 3000
    command: yarn start

